### ISSUE TITLE
Binding issues

### ISSUE THREAD

**Issue by rizuruu** [jdscodelab/Steam-Redesign#1]
I am getting these on running

`Exception thrown: 'System.NotSupportedException' in System.dll
Exception thrown: 'System.NotSupportedException' in PresentationCore.dll
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Windows.Media.ImageSource' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: ImageSourceConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
Exception thrown: 'System.NotSupportedException' in System.dll
Exception thrown: 'System.NotSupportedException' in PresentationCore.dll
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Windows.Media.ImageSource' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: ImageSourceConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
Exception thrown: 'System.NotSupportedException' in System.dll
Exception thrown: 'System.NotSupportedException' in PresentationCore.dll
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Windows.Media.ImageSource' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: ImageSourceConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
Exception thrown: 'System.NotSupportedException' in System.dll
Exception thrown: 'System.NotSupportedException' in PresentationCore.dll
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Windows.Media.ImageSource' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: ImageSourceConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
Exception thrown: 'System.NotSupportedException' in System.dll
Exception thrown: 'System.NotSupportedException' in PresentationCore.dll
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Windows.Media.ImageSource' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: ImageSourceConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
Exception thrown: 'System.NotSupportedException' in System.dll
Exception thrown: 'System.NotSupportedException' in PresentationCore.dll
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Windows.Media.ImageSource' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: ImageSourceConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
Exception thrown: 'System.NotSupportedException' in System.dll
Exception thrown: 'System.NotSupportedException' in PresentationCore.dll
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Windows.Media.ImageSource' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: ImageSourceConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
Exception thrown: 'System.NotSupportedException' in System.dll
Exception thrown: 'System.NotSupportedException' in PresentationCore.dll
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Windows.Media.ImageSource' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: ImageSourceConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
Exception thrown: 'System.NotSupportedException' in System.dll
Exception thrown: 'System.NotSupportedException' in PresentationCore.dll
System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Windows.Media.ImageSource' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: ImageSourceConverter cannot convert from (null).
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
'SteamRedesign.exe' (CLR v4.0.30319: SteamRedesign.exe): Loaded 'd:\softwares\visualstudio\common7\ide\commonextensions\microsoft\xamldiagnostics\Framework\x86\Microsoft.VisualStudio.DesignTools.WpfTap.dll'. 
'SteamRedesign.exe' (CLR v4.0.30319: SteamRedesign.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll'. 
'SteamRedesign.exe' (CLR v4.0.30319: SteamRedesign.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\SMDiagnostics.dll'. 
'SteamRedesign.exe' (CLR v4.0.30319: SteamRedesign.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Internals.dll'. 
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=WindowsCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=MacCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=SteamCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=WindowsCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=MacCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=SteamCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=WindowsCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=MacCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=SteamCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=WindowsCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=MacCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=SteamCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=WindowsCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=MacCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=SteamCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=WindowsCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=MacCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=SteamCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=WindowsCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=MacCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=SteamCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=WindowsCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=MacCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=SteamCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=WindowsCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=MacCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=TrendingCards'. BindingExpression:Path=SteamCompatible; DataItem=null; target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
`

**Comment by jdscodelab** [comment]
Hi, Rizwan.

Make sure your image element has TargetNullValue={x: Null} like below:
<Image Source="{Binding imagePath, TargetNullValue={x:Null}}"/>

Regards,
Junaid Shaikh

**Comment by jdscodelab** [comment]
You might not have a namescope where you are trying to bind, you could try to replace the "ElementName=TrendingCards" construct with "Source=TrendingCards"

**Comment by rizuruu** [comment]
I tried and this is what I get these kind of errors now:

`System.Windows.Data Error: 40 : BindingExpression path error: 'WindowsCompatible' property not found on 'object' ''String' (HashCode=-1895842090)'. BindingExpression:Path=WindowsCompatible; DataItem='String' (HashCode=-1895842090); target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 40 : BindingExpression path error: 'MacCompatible' property not found on 'object' ''String' (HashCode=-1895842090)'. BindingExpression:Path=MacCompatible; DataItem='String' (HashCode=-1895842090); target element is 'Path' (Name=''); target property is 'NoTarget' (type 'Object')
`
